### ISSUE TITLE
Params Does not Work when is pased to schedule a Job

### ISSUE THREAD

**Issue by andresmelian** [agenda/agenda-rest#56] opened 2019-06-28 16:14 UTC
Im Trying to create a Job with a Basic URL and schedule this Job using params to not repeat the same Job with different Params, but I check an the params are not sending like that into the schedule.

http://localhost:4040/api/job/now

This is the Body I sent: 
{	
	"name": "SapUp",
	"data": {
		"params":
		{
			"vm_name": "NVD-PW-CA5-SAP-VT-11",
			"instance": "nn",
			"ticket":"TICKETTEST08",
			"mail":"andres.melian@cositas.com"
		}
	}
}

This is the Job Definition Im Using

{
	"_id" : ObjectId("5d1638e15f48de2af1aace10"),
	"name" : "SapUp",
	"url" : "https://webstation.cositas.com:3700/api/sap_up",
	"method" : "POST"
}

the errror Im Recieving is 

{
	"_id" : ObjectId("5d163962bbc6042b04da0fe4"),
	"name" : "SapUp",
	"data" : {
		"params" : {
			"vm_name" : "NVD-PW-CA5-SAP-VT-11",
			"instance" : "nn",
			"ticket" : "TICKETTEST08",
			"mail" : "andres.melian@cositas.com"
		}
	},
	"type" : "normal",
	"priority" : 0,
	"nextRunAt" : null,
	"lastModifiedBy" : null,
	"lockedAt" : null,
	"lastRunAt" : ISODate("2019-06-28T15:59:32.224Z"),
	"failCount" : 1,
	"failReason" : "406 - {\"id\":406,\"msg\":\"Debe ingresar vm_name\"}", (Is Not recieving this Param)
	"failedAt" : ISODate("2019-06-28T15:59:32.379Z"),
	"lastFinishedAt" : ISODate("2019-06-28T15:59:32.379Z")

Is this an Issue of the agenda-rest or Im using wrong the npm.

Best regards
Andres

**Comment by sampathBlam** [comment] 2020-01-15 07:55
@andresmelian 
Can it be because of the special characters in the param name and the value ( Underscore and hyphen respectively)? Can you check if it is possible to get a success response if you do not send hyphenated value for `vm_name` ?

**Comment by sampathBlam** [comment] 2020-01-15 08:22
@andresmelian : Your job definition url seems to be `https://webstation.cositas.com:3700/api/sap_up`. It does not include the expected param names. Shouldn't your url in the job definition be `https://webstation.cositas.com:3700/api/sap_up/:vm_name/:instance/:ticket/:mail` ?

**Comment by geosp** [comment] 2020-03-11 13:30
We should probably close this issue. I have tested this code and it works as designed. Is there another reason to keep it opened?

**Comment by geosp** [comment] 2020-03-11 13:39
I should add some unit tests for this. @keyvan-m-sadeghi Is that OK?

**Comment by geosp** [comment] 2020-03-11 22:37
@keyvan-m-sadeghi I added the unit tests to test this functionality. I think we can close this thicket when #73 is merged.

**Comment by geosp** [comment] 2020-03-11 22:49
@andresmelian You can take a look at the relevant unit test for this feature here: https://github.com/agenda/agenda-rest/blob/62dd72e53e174a80eb891807a42f0c64db055831/test.js#L159-L167

**Comment by 2bigO** [comment] 2020-03-11 23:04
Great to hear, thanks @geosp :tada:

**Comment by 2bigO** [comment] 2020-03-12 04:04
Closing as #73 is now merged.

**Closed as completed** 2020-03-12 04:04 UTC
Labels: help wanted
